@startuml
autonumber
skinparam actorStyle awesome
actor Client as cl
participant Client_Application as cl_app
queue Queue as q
participant Desc_Application as ds_app
participant Engineer_Application as en_app
actor Engineer as en
database db


cl->cl_app: Запрос на создание \nзаявки на работу. \n**Передача данных:**\n*ФИО\n*Телефон\n*Адрес\n*Регион\n*Суть заявки\n*Дата исполнения
cl_app->q:\n**Передача данных:**\n*ФИО\n*Телефон\n*Адрес\n*Регион\n*Суть заявки\n*Дата исполнения
cl_app->db: Сохранение данных по клиенту
q->ds_app:Сообщение об актуальной заявке\n**Передача данных:**\n*ФИО\n*Телефон\n*Адрес\n*Регион\n*Суть заявки\n*Дата исполнения
ds_app-->q: Заявка в обработке\n**Передача данных:**\n*Статус заявки\n*Дата создания nзаявки
ds_app->ds_app: **Обработка заявки:**\n*Определение типа заявки\n*Определение Сложности заявки (int)\n*Определение даты исполнения заявки относительно сегодня
en->en_app: **Передача данных:**\n*ФИО\n*Номер телефона\n*Регион\n*График работы\n*Квалификация (int)\n*Статус доступности
en_app->db: Сохранение данных по инженеру
ds_app->db: Запрос данных по инженеру
db-->ds_app:Данные по инженеру
ds_app->ds_app: **Поиск матчинга между инженером и заявкой по параметрам:**\n*Регион кл.=Регион инж.\n*Сложности заявки <=Квалификация\n*День недели Даты исполнения=Один из дней недели Графика работы\n*Время Даты исполнения в диапазоне дня нед. из предыдущего п.\n*Статус доступности инженера=Доступен на вычисленный день и время
ds_app->db: Сохранение данных по заявке
ds_app->q:Сообщение об окончании обработки заявки\n**Передача данных:**\n*Статус заявки\n*Дата создания заявки\n*Дата исполнения заявки\n*ФИ инженера\n*Номер тел. инженера\n*Регион\n*Тип nзаявки
q-->ds_app:Данные по заявке приняты
q->cl_app:**Передача данных:**\n*Статус заявки\n*Дата создания заявки\n*Дата исполнения заявки\n*ФИ инженера\n*Номер тел. инженера
ds_app->en_app:**Передача данных:**\n*Статус заявки\n*Дата создания заявки\n*Дата исполнения заявки\n*ФИ клиента\n*Адрес клиента
cl_app->cl: **Передача данных:**\n*Статус заявки\n*Дата создания заявки\n*Дата исполнения заявки\n*ФИ инженера\n*Номер тел. инженера
en_app->en:**Передача данных:**\n*Статус заявки\n*Дата создания заявки\n*Дата исполнения заявки\n*ФИ клиента\n*Адрес клиента



@enduml